//
//  TokenResponse.swift
//  MostActivePosts
//
//  Created by Eugene Lobyr on 4/16/19.
//  Copyright © 2019 Eugene Lobyr. All rights reserved.
//

class TokenResponse: Codable {
    /// Your access token
    let accessToken: String
    /// The string "bearer"
    let tokenType: String
    /// A unique, per-device ID generated by your client. See note below. Only for https://oauth.reddit.com/grants/installed_client requests.
    let deviceId: String
    /// Seconds until the token expires
    let expiresIn: Double
    /// The scope of the token
    let scope: String
    
    enum CodingKeys: String, CodingKey {
        case accessToken = "access_token"
        case tokenType = "token_type"
        case deviceId = "device_id"
        case expiresIn = "expires_in"
        case scope
    }
}
